### ISSUE TITLE
棚架的材质错误 The material of the trellis is incorrect.

### ISSUE THREAD

**Issue by HanJiang-cn** [TeamTeaMC-Misc/Tea-the-Story#1]
棚架在放下时材质会乱跳。
（问：稻田的开垦方法与原版不同，请问是如何开垦?  请问烘培模式如何激活？）
![2024-08-29_20 23 46](https://github.com/user-attachments/assets/bbdc5b4a-2294-4fff-b717-3519e8617b2c)
如果您回复我，我会更好的编写相关的帖子。谢谢！

When the scaffold is put down, the texture jumps around erratically.
(How is the paddy field cultivated differently from the original version? How to activate the baking mode?)
If you reply to me, I will be able to write the relevant posts better. Thank you!

**Comment by joe-vettek** [comment]
抱歉这里奇怪我没收到邮件， 目前有进度来做指引，这个材质的问题暂时没有其他报道，理论上应该不会跳的。

Sorry for the strange thing here. I didn’t receive the email. There is currently progress to provide guidance. There are no other reports on this material problem for the time being. In theory, it should not jump.

**Comment by HanJiang-cn** [comment]
> 抱歉这里奇怪我没收到邮件， 目前有进度来做指引，这个材质的问题暂时没有其他报道，理论上应该不会跳的。
> 
> Sorry for the strange thing here. I didn’t receive the email. There is currently progress to provide guidance. There are no other reports on this material problem for the time being. In theory, it should not jump.

感谢您的回复，刚刚我下载了较新的版本去测试，确实发现该问题已经解决。
Thank you for your response. I just downloaded the newer version to test, and indeed, I found that the issue has been resolved.
