### ISSUE TITLE
1.19.2 request

### ISSUE THREAD

**Issue by ray-bonaparte** [TeamTeaMC-Misc/Tea-the-Story#2]

**Comment by joe-vettek** [comment]
目前的情况来看，这个版本似乎游玩的人很少，大约是1.20的1/10。

Judging from the current situation, it seems that very few people are playing this version, about 1/10 of 1.20.

**Comment by joe-vettek** [comment]
We don't have that much time.

**Comment by ray-bonaparte** [comment]
sign

joe-vettek ***@***.***> 于 2024年11月17日周日 01:21写道：
